{
 "title": "Z-Box Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "peer",
    "label": "Peer",
    "query": {
     "query": "label_values(wireguard_sent_bytes_total{public_key=\"$peer\"},$peer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Z-Box host health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory used %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Root disk usage %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "(1 - (node_filesystem_avail_bytes\r\n      / node_filesystem_size_bytes)) * 100\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network throughput on wg0",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{device=\"wg0\"}[5m])\r\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{device=\"wg0\"}[5m])\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Wireguard Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Handshake age (seconds)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(public_key) (wireguard_latest_handshake_seconds)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total tunnel traffic (bytes/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "sum by(interface) (rate(wireguard_sent_bytes_total[5m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(interface) (rate(wireguard_received_bytes_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Per-peer details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "rate(wireguard_sent_bytes_total{public_key=\"$peer\"}[5m]) / 8",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(wireguard_received_bytes_total{public_key=\"$peer\"}[5m]) / 8",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Peer handshake age",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wireguard_latest_handshake_seconds{public_key=\"$peer\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}